### ISSUE TITLE
Tool freezes when assiging Black (#000000) to a material or any color field.

### ISSUE THREAD

**Issue by Manukineko** [YoYoGames/3D-2D#1]
- Import a 3D files.
- select the color field under a material
- select Black either with the Color Picker or with a HEX value
- the tool freeze.

Running it in debug mode and pausing it show that it as enter an infinite `while` loop in the function `GUI_ReatToString` in the `gui_utils.gml` script asset at line 256.
`_stringLength` is going negative.

![SpriteTool_-_GameMaker-Beta_22 09 07_094837_102](https://user-images.githubusercontent.com/43104858/188770013-0afff879-4f71-4602-8376-bc19d44da32b.png)

**Comment by pkraif** [comment]
Resolved in 31cad35f6c4f0e1705d66af978989edc649393aa
